### ISSUE TITLE
Image processing issue

### ISSUE THREAD

**Issue by glenrobson** [glenrobson/iiif-tiler#17]
Martim found:

```
9917e57fffe7 - iiify - Processing: 001AAN005147
Zoom level 5
Exception in thread "main" java.lang.RuntimeException: Error doing rescale. Target size was 256x1 but must be at least 3x3.
```

Image: https://imaginerio-images.s3.us-east-1.amazonaws.com/iiif/001AAN005147/full/max/0/default.jpg

From [container](https://github.com/imaginerio/situated-views-etl/tree/feature/dagster-docker). Container commands:

```
docker build -t etl .
docker run etl dagster pipeline execute -f pipelines/iiif_pipeline.py --preset test
```

Python wrapper:

https://github.com/imaginerio/situated-views-etl/blob/2abf0665955a6486b2067fb49aa899f4b26b46b0/src/solids/iiif.py#L454

**Comment by martimpassos** [comment]
Ok I _think_ I know what's up: it is probably breaking on cases such as this:
![image](https://user-images.githubusercontent.com/49573683/137215528-b05ded78-4fc0-4cfc-b48a-ec77a8777c17.png)
