### ISSUE TITLE
setting ID as argument?

### ISSUE THREAD

**Issue by martimpassos** [glenrobson/iiif-tiler#21]
Hi @glenrobson, is it currently possible to set the manifest ID as argument for the tiler?

**Comment by glenrobson** [comment]
No, but that is a good idea. Let me look into it.

**Comment by d-flood** [comment]
I've been experimenting with the tiler and am really pleased with it. I also would like to pass an argument for the `id`. Right now I am setting the correct URI with a post processing script.
